#よく使う変数
# TARGET = main
# NAME = 
# SRCS = 
# OBJS = 
# CC = gcc
# CFLAG = -wall
# INC = -I../INC
# LIB = 

#CC=gcc
# CFLAG = -Wall
# TARGET = myprogram

# all: $(TARGET)
	
# $(TARGET): main.o
# 	$(CC) -g $(CFLAG) -o $(TARGET) main.o 

# main.o: main.c 
# 	$(CC) -g $(CFLAG) -c main.c -o main.o

# clean:
# 	rm *.o 
# 	rm $(TARGET)


# all: mai1.o 
# 	gcc -g -o myprogram main1.o 

# main1.o: main1.c 
# 	gcc -g -c main1.c -o main1.o

# clean:
# 	rm *.o 
# 	rm myprogram


all: main2.o 
	gcc -g -o myprogram main2.o 

main2.o: main2.c 
	gcc -g -c main2.c -o main2.o

clean:
	rm *.o 
	rm myprogram


