all: ex1 ex2 ex3 ex4

ex1: ex1.c 
	gcc -g -c ex1.c -o ex1.o

ex2: ex2.c
	gcc -g -c ex2.c -o ex2.o

ex3: ex3.c
	gcc -g -c ex3.c -o ex3.o 

ex4: ex4.c
	gcc -g -W -Wall ex4.c -o ex4.o 

clean:
	rm *.o 


